name: baata
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  firebase_messaging: ^11.2.5
  http: ^0.13.4
  image_picker: ^0.8.4+4
  flutter_contacts: ^1.1.2
  shared_preferences: ^2.0.12
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  video_player: ^2.2.14

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_cropper:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - flags/AF.jpg
     - flags/AX.jpg
     - flags/AL.jpg
     - flags/DZ.jpg
     - flags/AS.jpg
     - flags/AD.jpg
     - flags/AO.jpg
     - flags/AI.jpg
     - flags/AQ.jpg
     - flags/AG.jpg
     - flags/AR.jpg
     - flags/AM.jpg
     - flags/AW.jpg
     - flags/AU.jpg
     - flags/AT.jpg
     - flags/AZ.jpg
     - flags/BS.jpg
     - flags/BH.jpg
     - flags/BD.jpg
     - flags/BB.jpg
     - flags/BY.jpg
     - flags/BE.jpg
     - flags/BZ.jpg
     - flags/BJ.jpg
     - flags/BM.jpg
     - flags/BT.jpg
     - flags/BO.jpg
     - flags/BA.jpg
     - flags/BW.jpg
     - flags/BR.jpg
     - flags/IO.jpg
     - flags/BN.jpg
     - flags/BG.jpg
     - flags/BF.jpg
     - flags/BI.jpg
     - flags/KH.jpg
     - flags/CM.jpg
     - flags/CA.jpg
     - flags/CV.jpg
     - flags/KY.jpg
     - flags/CF.jpg
     - flags/TD.jpg
     - flags/CL.jpg
     - flags/CN.jpg
     - flags/CX.jpg
     - flags/CC.jpg
     - flags/CO.jpg
     - flags/KM.jpg
     - flags/CG.jpg
     - flags/CK.jpg
     - flags/CR.jpg
     - flags/HR.jpg
     - flags/CU.jpg
     - flags/CY.jpg
     - flags/CZ.jpg
     - flags/CD.jpg
     - flags/DK.jpg
     - flags/DJ.jpg
     - flags/DM.jpg
     - flags/DO.jpg
     - flags/EC.jpg
     - flags/EG.jpg
     - flags/SV.jpg
     - flags/GQ.jpg
     - flags/ER.jpg
     - flags/EE.jpg
     - flags/SZ.jpg
     - flags/ET.jpg
     - flags/FK.jpg
     - flags/FO.jpg
     - flags/FJ.jpg
     - flags/FI.jpg
     - flags/FR.jpg
     - flags/GF.jpg
     - flags/PF.jpg
     - flags/GA.jpg
     - flags/GM.jpg
     - flags/GE.jpg
     - flags/DE.jpg
     - flags/GH.jpg
     - flags/GI.jpg
     - flags/GR.jpg
     - flags/GL.jpg
     - flags/GD.jpg
     - flags/GP.jpg
     - flags/GU.jpg
     - flags/GT.jpg
     - flags/GG.jpg
     - flags/GN.jpg
     - flags/GW.jpg
     - flags/GY.jpg
     - flags/HT.jpg
     - flags/VA.jpg
     - flags/HN.jpg
     - flags/HK.jpg
     - flags/HU.jpg
     - flags/IS.jpg
     - flags/IN.jpg
     - flags/ID.jpg
     - flags/IR.jpg
     - flags/IQ.jpg
     - flags/IE.jpg
     - flags/IM.jpg
     - flags/IL.jpg
     - flags/IT.jpg
     - flags/CI.jpg
     - flags/JM.jpg
     - flags/JP.jpg
     - flags/JE.jpg
     - flags/JO.jpg
     - flags/KZ.jpg
     - flags/KE.jpg
     - flags/KI.jpg
     - flags/KP.jpg
     - flags/KR.jpg
     - flags/XK.jpg
     - flags/KW.jpg
     - flags/KG.jpg
     - flags/LA.jpg
     - flags/LV.jpg
     - flags/LB.jpg
     - flags/LS.jpg
     - flags/LR.jpg
     - flags/LY.jpg
     - flags/LI.jpg
     - flags/LT.jpg
     - flags/LU.jpg
     - flags/MO.jpg
     - flags/MG.jpg
     - flags/MW.jpg
     - flags/MY.jpg
     - flags/MV.jpg
     - flags/ML.jpg
     - flags/MT.jpg
     - flags/MH.jpg
     - flags/MQ.jpg
     - flags/MR.jpg
     - flags/MU.jpg
     - flags/YT.jpg
     - flags/MX.jpg
     - flags/FM.jpg
     - flags/MD.jpg
     - flags/MC.jpg
     - flags/MN.jpg
     - flags/ME.jpg
     - flags/MS.jpg
     - flags/MA.jpg
     - flags/MZ.jpg
     - flags/MM.jpg
     - flags/NA.jpg
     - flags/NR.jpg
     - flags/NP.jpg
     - flags/NL.jpg
     - flags/NC.jpg
     - flags/NZ.jpg
     - flags/NI.jpg
     - flags/NE.jpg
     - flags/NG.jpg
     - flags/NU.jpg
     - flags/NF.jpg
     - flags/MK.jpg
     - flags/MP.jpg
     - flags/NO.jpg
     - flags/OM.jpg
     - flags/PK.jpg
     - flags/PW.jpg
     - flags/PS.jpg
     - flags/PA.jpg
     - flags/PG.jpg
     - flags/PY.jpg
     - flags/PE.jpg
     - flags/PH.jpg
     - flags/PN.jpg
     - flags/PL.jpg
     - flags/PT.jpg
     - flags/PR.jpg
     - flags/QA.jpg
     - flags/RE.jpg
     - flags/RO.jpg
     - flags/RU.jpg
     - flags/RW.jpg
     - flags/BL.jpg
     - flags/SH.jpg
     - flags/KN.jpg
     - flags/LC.jpg
     - flags/MF.jpg
     - flags/PM.jpg
     - flags/VC.jpg
     - flags/WS.jpg
     - flags/SM.jpg
     - flags/ST.jpg
     - flags/SA.jpg
     - flags/SN.jpg
     - flags/RS.jpg
     - flags/SC.jpg
     - flags/SL.jpg
     - flags/SG.jpg
     - flags/SX.jpg
     - flags/SK.jpg
     - flags/SI.jpg
     - flags/SB.jpg
     - flags/SO.jpg
     - flags/ZA.jpg
     - flags/GS.jpg
     - flags/SS.jpg
     - flags/ES.jpg
     - flags/LK.jpg
     - flags/SD.jpg
     - flags/SR.jpg
     - flags/SJ.jpg
     - flags/SE.jpg
     - flags/CH.jpg
     - flags/SY.jpg
     - flags/TW.jpg
     - flags/TJ.jpg
     - flags/TZ.jpg
     - flags/TH.jpg
     - flags/TL.jpg
     - flags/TG.jpg
     - flags/TK.jpg
     - flags/TO.jpg
     - flags/TT.jpg
     - flags/TN.jpg
     - flags/TR.jpg
     - flags/TM.jpg
     - flags/TC.jpg
     - flags/TV.jpg
     - flags/UG.jpg
     - flags/UA.jpg
     - flags/AE.jpg
     - flags/GB.jpg
     - flags/US.jpg
     - flags/US.jpg
     - flags/UY.jpg
     - flags/UZ.jpg
     - flags/VU.jpg
     - flags/VE.jpg
     - flags/VN.jpg
     - flags/VG.jpg
     - flags/VI.jpg
     - flags/WF.jpg
     - flags/YE.jpg
     - flags/ZM.jpg
     - flags/ZW.jpg

     
     

   
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
