// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB3eANWNxT1XS1KuXar5SQ_J6I_5gT9cU',
    appId: '1:320232442272:android:2536895e1804d7c15f7cc5',
    messagingSenderId: '320232442272',
    projectId: 'batsapp-6969',
    storageBucket: 'batsapp-6969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn8e6zQTfatkcNqaYt7OsmqcBsJe1jfxY',
    appId: '1:320232442272:ios:19dd8c16be9eb5b25f7cc5',
    messagingSenderId: '320232442272',
    projectId: 'batsapp-6969',
    storageBucket: 'batsapp-6969.appspot.com',
    androidClientId: '320232442272-88agadrf8fpq1d4a6fncml9aip0lsag7.apps.googleusercontent.com',
    iosClientId: '320232442272-nj7aj2b9keq3ln3b2lg1s8iv8u3colik.apps.googleusercontent.com',
    iosBundleId: 'com.example.baata',
  );
}
